OAuth V2 documentation added
Deskera/Developer-Documentation pull request #3
Opened 2020-11-30 12:06 UTC by Ankush1994

2020-11-30 17:03 UTC, archit-p requested changes

2020-11-30 17:03 UTC, archit-p commented on docs/books/authenticationv2.md
> +A token is a piece of data that has no meaning or use on its own, but combined with the correct tokenization system, becomes a vital player in securing your application. Token based authentication wo
Typo in `signed toke` -> `signed token`

2020-11-30 17:03 UTC, archit-p commented on docs/books/authenticationv2.md
> +The Authentication V2 API enables you to manage all aspects of user identity when you use Auth0. It offers endpoints so your users can log in, sign up, log out, access APIs, and more.
Auth0 is a company that provides JWT auth, I don't think it was intended to have them mentioned here

2020-11-30 17:03 UTC, archit-p commented on docs/books/oauthv2.md
> +Once on the Deskera App auth page, the user would be prompted to input his/her Deskera user name and password, select the Organization we would like to connect and asked to authorize the app. The use
We don't prompt user to enter user name and password anymore

2020-11-30 17:03 UTC, archit-p commented on docs/books/oauthv2.md
> +After the user connects their existing account to your platform, we'll make an API call to the `redirect_uri` (provided at the time of partner registration) with the below parameters
We are redirecting now, so no API call

2020-12-01 02:37 UTC, Ankush1994 commented on docs/books/oauthv2.md
> +After the user connects their existing account to your platform, we'll make an API call to the `redirect_uri` (provided at the time of partner registration) with the below parameters
Done

2020-12-01 02:37 UTC, Ankush1994 commented on docs/books/oauthv2.md
> +Once on the Deskera App auth page, the user would be prompted to input his/her Deskera user name and password, select the Organization we would like to connect and asked to authorize the app. The use
removed

2020-12-01 02:38 UTC, Ankush1994 commented on docs/books/authenticationv2.md
> +The Authentication V2 API enables you to manage all aspects of user identity when you use Auth0. It offers endpoints so your users can log in, sign up, log out, access APIs, and more.
Removed reference to Auth0

2020-12-01 02:38 UTC, Ankush1994 commented on docs/books/authenticationv2.md
> +A token is a piece of data that has no meaning or use on its own, but combined with the correct tokenization system, becomes a vital player in securing your application. Token based authentication wo
Fixed

2020-12-01 03:08 UTC, merged